on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: slither-static-analysis
    uses: luisfontes19/slither-static-analysis-action@v0.3.3

    


    
    
        

