on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci --also=dev
    - name: Run Linter
      run: |
        npm run lint > linter-log.txt 2>&1
        if [ $? -ne 0 ]; then
          echo "##vso[task.setvariable variable=linterLog]${{ env.cat linter-log.txt | sed '1,/> eslint ./d;/npm ERR!/,$d' | sed '/./,$!d' | sed ':a;N;$!ba;s/
/%0D%0A/g' }}"
